### ISSUE TITLE
可见光和红外的原始分辨率必须要保持一致吗？

### ISSUE THREAD

**Issue by AbandonedWarlord** [wdhudiekou/UMF-CMGR#14]
作者您好，
在我的数据集上可见光和红外图像的原始分辨率不一致，于是我直接resize之后开始训练，并不像您提供的FILR数据集每对图像分辨率保持一致。于是我的数据集在配准测试时，ir_reg中输出的配准结果边缘出现了扭曲和黑边，我认为是关键点不匹配导致的。
我想请教一下这个问题是什么原因，怎么去解决。
期待您的回复！
       谢谢！

**Comment by wdhudiekou** [comment]
您好！感谢您的关注。据我猜测，您的红外图像和可见光图像在内容上以及拍摄的角度上或许也存在一些差别，因此在配准的过程中，两幅图像的公共内容应该是能够对齐的，这时二者的差别内容就会因为无法对齐而产生扭曲，同时，因为对齐的过程中扭曲，旋转，平移等变换的发生，而图像的尺寸又是固定的，因此会补充值为0的像素，也就产生了您提到的黑边。希望能帮到您。
再次感谢您对该工作的关注！
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Mon, Sep 19, 2022 09:33 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[wdhudiekou/UMF-CMGR] 可见光和红外的原始分辨率必须要保持一致吗？ (Issue #14)

&nbsp;



 
作者您好，
 在我的数据集上可见光和红外图像的原始分辨率不一致，于是我直接resize之后开始训练，并不像您提供的FILR数据集每对图像分辨率保持一致。于是我的数据集在配准测试时，ir_reg中输出的配准结果边缘出现了扭曲和黑边，我认为是关键点不匹配导致的。
 我想请教一下这个问题是什么原因，怎么去解决。
 期待您的回复！
 谢谢！
