### ISSUE TITLE
CSPTN

### ISSUE THREAD

**Issue by ljw1000000** [wdhudiekou/UMF-CMGR#18]
师兄您好：
  我在使用您提供的https://pan.baidu.com/s/1JO4hjdaXPUScCI6oFtPEnQ) (code: i9ju) of CPSTN 模型，生成伪红外图像时，遇到这个错误，是否您提供的预训练模型和代码不匹配？能重新穿个合适的么
RuntimeError: Error(s) in loading state_dict for ResnetGenerator:
	Missing key(s) in state_dict: "model.10.conv_block.6.weight", "model.10.conv_block.6.bias", "model.11.conv_block.6.weight", "model.11.conv_block.6.bias", "model.12.conv_block.6.weight", "model.12.conv_block.6.bias", "model.13.conv_block.6.weight", "model.13.conv_block.6.bias", "model.14.conv_block.6.weight", "model.14.conv_block.6.bias", "model.15.conv_block.6.weight", "model.15.conv_block.6.bias", "model.16.conv_block.6.weight", "model.16.conv_block.6.bias", "model.17.conv_block.6.weight", "model.17.conv_block.6.bias", "model.18.conv_block.6.weight", "model.18.conv_block.6.bias". 
	Unexpected key(s) in state_dict: "model.10.conv_block.5.weight", "model.10.conv_block.5.bias", "model.11.conv_block.5.weight", "model.11.conv_block.5.bias", "model.12.conv_block.5.weight", "model.12.conv_block.5.bias", "mod

**Comment by xiaomudsg** [comment]
> 师兄您好： 我在使用您提供的 https://pan.baidu.com/s/1JO4hjdaXPUScCI6oFtPEnQ） （code： i9ju） of CPSTN 模型，生成伪红外图像时，遇到这个错误，是否您提供的预训练模型和代码不匹配？能重新穿个合适的么 RuntimeError： Error（s） in loading state_dict for ResnetGenerator： Missing key（s） in state_dict： “model.10.conv_block.6.weight”， “model.10.conv_block.6.bias”， “model.11.conv_block.6.weight”， “model.11.conv_block.6.bias”， “model.12.conv_block.6.weight”， “model.12.conv_block.6.bias”， “model.13.conv_block.6.weight“， ”model.13.conv_block.6.bias“， ”model.14.conv_block.6.weight“， ”model.14.conv_block.6.bias“， ”model.15.conv_block.6.weight“， ”model.15.conv_block.6.bias“， ”model.16.conv_block.6.weight“， ”model.16.conv_block.6.bias“， ”model.17.conv_block.6.weight“， ”model.17.conv_block.6.bias“， ”model.18.conv_block.6.weight“， ”model.18.conv_block.6.bias“. state_dict中意外的键：“model.10.conv_block.5.weight”、“model.10.conv_block.5.bias”、“model.11.conv_block.5.weight”、“model.11.conv_block.5.bias”、“model.12.conv_block.5.weight”、“model.12.conv_block.5.bias”、“mod

请问您最后是怎么解决的呀？
