### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by scl1997** [wdhudiekou/UMF-CMGR#2]
warped, affine_param = self.trs(input) 为什么trs函数报错
说是因为返回一个值要用两个变量接受

**Comment by wdhudiekou** [comment]
It is suggested to check your code. The raw code doesn't make similar mistakes.

**Comment by scl1997** [comment]
你好，请问可以提供一下配准的模型参数吗
