### ISSUE TITLE
Google Drive Link Request

### ISSUE THREAD

**Issue by MMarvasti** [wdhudiekou/UMF-CMGR#29]
Hello,

Could you please provide a link to your training and testing data, pre-trained models, etc. on Google Drive?

Thank you in advance.
Mojtaba

**Comment by wdhudiekou** [comment]
Hello,
      
        Thank you for your interest in my work. The Google Drive link for training and testing data is https://drive.google.com/drive/folders/1C8Q1jBZ2VRbc4suuLdD8_eUJk9SaLgtL.

**Comment by wdhudiekou** [comment]
The Google Drive link for pre-trained models is https://drive.google.com/drive/folders/1k7IH-sbF3UWAM3MckcmXadGpfDR34FrZ.

**Comment by MMarvasti** [comment]
Thank you so much.

Mojtaba

**Comment by MMarvasti** [comment]
Still waiting for your access permission...
