### ISSUE TITLE
您好，请问kornia版本有什么要求吗，或者对输入的红外和可见光数据有什么要求没有，我的输入都是灰度图 

### ISSUE THREAD

**Issue by scl1997** [wdhudiekou/UMF-CMGR#3]
我在获取变形红外图像和训练配准和测试配准都遇到同样的问题
warped, affine_param = self.trs(input)  # [batch_size, 3, 3]
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by wdhudiekou** [comment]
The version of the Kornia package is 0.5.11

**Comment by scl1997** [comment]
能用了 谢谢
