### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by edoardoMalaspina** [wdhudiekou/UMF-CMGR#47]
Hello, i'm really interested in this work and i'm looking forward to try CPSTN to generate pseudo-ir images, but unfortunately i cannot download your pretrained model from baidun because from Europe is really difficult to create an account. Would it be possible for you to make it available from other sources (like google drive) or to let me have the pre-trained models in another way?

Thank you in advance!

**Comment by wdhudiekou** [comment]
You can download it from the following link: https://drive.google.com/drive/folders/1C8Q1jBZ2VRbc4suuLdD8_eUJk9SaLgtL?usp=sharing

**Comment by edoardoMalaspina** [comment]
Thank you really much for your fast answer
