### ISSUE TITLE
请问test_reg中ir_w代表什么

### ISSUE THREAD

**Issue by scl1997** [wdhudiekou/UMF-CMGR#5]

**Comment by wdhudiekou** [comment]
warped infrared images

**Comment by scl1997** [comment]
我还想再请问一下，配准的图像和伪红外图像一样大小对吗，伪红外图像怎么生成呢



---- 回复的原邮件 ----
| 发件人 | Di ***@***.***> |
| 日期 | 2022年05月24日 16:06 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [wdhudiekou/UMF-CMGR] 请问test_reg中ir_w代表什么 (Issue #5) |

warped infrared images
