### ISSUE TITLE
关于CPSTN训练问题

### ISSUE THREAD

**Issue by code2497** [wdhudiekou/UMF-CMGR#52]
请问CPSTN是使用已配准的图像对进行训练的吗？我用未配准的图像对进行训练的时候，生成的伪红外图像会产生形变。

**Comment by wdhudiekou** [comment]
CPSTN的设计初衷是通过风格迁移从VIS图像生成伪IR图像，因此，我是用多个数据集的源图像混合在一起变成一个大规模数据集训练的CPST模型，然后在训练后续配准和融合的时候才输入不对齐图像，这时的CPST是冻结参数的。如果你需要在其他数据集上训练的话，最好用对齐的图像。

**Comment by code2497** [comment]
了解，感谢回复

**Comment by hongzhitao** [comment]
> 了解，感谢回复

请问作者的意思是整个配准融合网络只能用对齐的图像训练吗？在测试中，怎么用这个网络配准真实环境采集的未对齐的图像呢？
