### ISSUE TITLE
 pseudo infrared images是不是就代表配准好的红外图像

### ISSUE THREAD

**Issue by scl1997** [wdhudiekou/UMF-CMGR#8]

**Comment by hli1221** [comment]
这个只是代表根据可见光图像生成的红外图像，和真实红外图像还有差别

**Comment by wdhudiekou** [comment]
Thanks for your answer. In fact, pseudo infrared images are generated by our cross-modality perceptual style transfer network taking visible images as inputs. I hope it helps.
